# SPDX-License-Identifier: LGPL-2.1-or-later
# Runtime directories owned by RustD.

d /run/rustd              0755 root root -
d /run/user               0755 root root -
d /run/rustd/system       0755 root root -
d /run/rustd/journal      0755 root root -
d /run/rustd/units        0755 root root -
d /run/rustd/dynamic-uid  0700 root root -
d /run/rustd/notify       0700 root root -
d /run/rustd/resolve      0755 rustd-resolve rustd-resolve -
d /run/rustd/sessions     0755 root root -
d /run/rustd/users        0755 root root -
d /run/rustd/seats        0755 root root -
d /run/dbus               0755 root root -
d /run/avahi-daemon        0755 avahi avahi -
d /run/chrony             0750 chrony chrony -
d /run/udev               0755 root root -
d /run/udev/data          0755 root root -

# Char devices must stay world-accessible; some boots leave them 0660.
z /dev/null               0666 root root -
z /dev/zero               0666 root root -
z /dev/full               0666 root root -
z /dev/random             0666 root root -
z /dev/urandom            0666 root root -
z /dev/tty                0666 root tty  -
