# SPDX-License-Identifier: LGPL-2.1-or-later
# Runtime directories owned by RustD.

d /run/rustd              0755 root root -
d /run/rustd/system       0755 root root -
d /run/rustd/journal      0755 root root -
d /run/rustd/units        0755 root root -
d /run/rustd/dynamic-uid  0700 root root -
d /run/rustd/notify       0700 root root -
d /run/rustd/resolve      0755 rustd-resolve rustd-resolve -
