// SPDX-License-Identifier: LGPL-2.1-or-later
// Generated from the pinned systemd v261 syscall filter-set table.

const GROUP_AIO: &[&str] = &[
    "io_cancel",
    "io_destroy",
    "io_getevents",
    "io_pgetevents",
    "io_pgetevents_time64",
    "io_setup",
    "io_submit",
    "io_uring_enter",
    "io_uring_register",
    "io_uring_setup",
];
const GROUP_BASIC_IO: &[&str] = &[
    "_llseek",
    "close",
    "close_range",
    "dup",
    "dup2",
    "dup3",
    "llseek",
    "lseek",
    "pread64",
    "preadv",
    "preadv2",
    "pwrite64",
    "pwritev",
    "pwritev2",
    "read",
    "readv",
    "write",
    "writev",
];
const GROUP_CHOWN: &[&str] = &[
    "chown", "chown32", "fchown", "fchown32", "fchownat", "lchown", "lchown32",
];
const GROUP_CLOCK: &[&str] = &[
    "adjtimex",
    "clock_adjtime",
    "clock_adjtime64",
    "clock_settime",
    "clock_settime64",
    "settimeofday",
];
const GROUP_CPU_EMULATION: &[&str] = &[
    "modify_ldt",
    "subpage_prot",
    "switch_endian",
    "vm86",
    "vm86old",
];
const GROUP_DEBUG: &[&str] = &[
    "lookup_dcookie",
    "perf_event_open",
    "pidfd_getfd",
    "ptrace",
    "rtas",
    "s390_runtime_instr",
    "sys_debug_setcontext",
];
const GROUP_DEFAULT: &[&str] = &[
    "@sandbox",
    "arch_prctl",
    "brk",
    "cacheflush",
    "clock_getres",
    "clock_getres_time64",
    "clock_gettime",
    "clock_gettime64",
    "clock_nanosleep",
    "clock_nanosleep_time64",
    "execve",
    "exit",
    "exit_group",
    "futex",
    "futex_time64",
    "futex_waitv",
    "get_robust_list",
    "get_thread_area",
    "getegid",
    "getegid32",
    "geteuid",
    "geteuid32",
    "getgid",
    "getgid32",
    "getgroups",
    "getgroups32",
    "getpgid",
    "getpgrp",
    "getpid",
    "getppid",
    "getrandom",
    "getresgid",
    "getresgid32",
    "getresuid",
    "getresuid32",
    "getrlimit",
    "getsid",
    "gettid",
    "gettimeofday",
    "getuid",
    "getuid32",
    "lsm_get_self_attr",
    "lsm_list_modules",
    "membarrier",
    "mmap",
    "mmap2",
    "mprotect",
    "mseal",
    "munmap",
    "nanosleep",
    "pause",
    "prlimit64",
    "restart_syscall",
    "riscv_flush_icache",
    "riscv_hwprobe",
    "rseq",
    "rt_sigreturn",
    "sched_getaffinity",
    "sched_yield",
    "set_robust_list",
    "set_thread_area",
    "set_tid_address",
    "set_tls",
    "sigreturn",
    "time",
    "ugetrlimit",
    "uretprobe",
];
const GROUP_FILE_SYSTEM: &[&str] = &[
    "access",
    "chdir",
    "chmod",
    "close",
    "creat",
    "faccessat",
    "faccessat2",
    "fallocate",
    "fchdir",
    "fchmod",
    "fchmodat",
    "fchmodat2",
    "fcntl",
    "fcntl64",
    "fgetxattr",
    "file_getattr",
    "file_setattr",
    "flistxattr",
    "fremovexattr",
    "fsetxattr",
    "fstat",
    "fstat64",
    "fstatat",
    "fstatat64",
    "fstatfs",
    "fstatfs64",
    "ftruncate",
    "ftruncate64",
    "futimesat",
    "getcwd",
    "getdents",
    "getdents64",
    "getxattr",
    "getxattrat",
    "inotify_add_watch",
    "inotify_init",
    "inotify_init1",
    "inotify_rm_watch",
    "lgetxattr",
    "link",
    "linkat",
    "listmount",
    "listxattr",
    "listxattrat",
    "llistxattr",
    "lremovexattr",
    "lsetxattr",
    "lstat",
    "lstat64",
    "mkdir",
    "mkdirat",
    "mknod",
    "mknodat",
    "newfstat",
    "newfstatat",
    "oldfstat",
    "oldlstat",
    "oldstat",
    "open",
    "open_tree",
    "openat",
    "openat2",
    "readlink",
    "readlinkat",
    "removexattr",
    "removexattrat",
    "rename",
    "renameat",
    "renameat2",
    "rmdir",
    "setxattr",
    "setxattrat",
    "stat",
    "stat64",
    "statfs",
    "statfs64",
    "statmount",
    "statx",
    "symlink",
    "symlinkat",
    "truncate",
    "truncate64",
    "unlink",
    "unlinkat",
    "utime",
    "utimensat",
    "utimensat_time64",
    "utimes",
];
const GROUP_IO_EVENT: &[&str] = &[
    "_newselect",
    "epoll_create",
    "epoll_create1",
    "epoll_ctl",
    "epoll_ctl_old",
    "epoll_pwait",
    "epoll_pwait2",
    "epoll_wait",
    "epoll_wait_old",
    "eventfd",
    "eventfd2",
    "poll",
    "ppoll",
    "ppoll_time64",
    "pselect6",
    "pselect6_time64",
    "select",
];
const GROUP_IPC: &[&str] = &[
    "ipc",
    "memfd_create",
    "mq_getsetattr",
    "mq_notify",
    "mq_open",
    "mq_timedreceive",
    "mq_timedreceive_time64",
    "mq_timedsend",
    "mq_timedsend_time64",
    "mq_unlink",
    "msgctl",
    "msgget",
    "msgrcv",
    "msgsnd",
    "pipe",
    "pipe2",
    "process_madvise",
    "process_vm_readv",
    "process_vm_writev",
    "semctl",
    "semget",
    "semop",
    "semtimedop",
    "semtimedop_time64",
    "shmat",
    "shmctl",
    "shmdt",
    "shmget",
];
const GROUP_KEYRING: &[&str] = &["add_key", "keyctl", "request_key"];
const GROUP_KNOWN: &[&str] = &["@obsolete", "@__known_native__"];
const GROUP_MEMLOCK: &[&str] = &["mlock", "mlock2", "mlockall", "munlock", "munlockall"];
const GROUP_MODULE: &[&str] = &["delete_module", "finit_module", "init_module"];
const GROUP_MOUNT: &[&str] = &[
    "chroot",
    "fsconfig",
    "fsmount",
    "fsopen",
    "fspick",
    "mount",
    "mount_setattr",
    "move_mount",
    "open_tree_attr",
    "pivot_root",
    "umount",
    "umount2",
];
const GROUP_NETWORK_IO: &[&str] = &[
    "accept",
    "accept4",
    "bind",
    "connect",
    "getpeername",
    "getsockname",
    "getsockopt",
    "listen",
    "recv",
    "recvfrom",
    "recvmmsg",
    "recvmmsg_time64",
    "recvmsg",
    "send",
    "sendmmsg",
    "sendmsg",
    "sendto",
    "setsockopt",
    "shutdown",
    "socket",
    "socketcall",
    "socketpair",
];
const GROUP_OBSOLETE: &[&str] = &[
    "_sysctl",
    "afs_syscall",
    "bdflush",
    "break",
    "create_module",
    "ftime",
    "get_kernel_syms",
    "getpmsg",
    "gtty",
    "idle",
    "lock",
    "mpx",
    "prof",
    "profil",
    "putpmsg",
    "query_module",
    "security",
    "sgetmask",
    "ssetmask",
    "stime",
    "stty",
    "sysfs",
    "tuxcall",
    "ulimit",
    "uselib",
    "ustat",
    "vserver",
];
const GROUP_PKEY: &[&str] = &["pkey_alloc", "pkey_free", "pkey_mprotect"];
const GROUP_PRIVILEGED: &[&str] = &[
    "@chown",
    "@clock",
    "@module",
    "@raw-io",
    "@reboot",
    "@swap",
    "_sysctl",
    "acct",
    "bpf",
    "capset",
    "chroot",
    "fanotify_init",
    "fanotify_mark",
    "nfsservctl",
    "open_by_handle_at",
    "pivot_root",
    "quotactl",
    "quotactl_fd",
    "setdomainname",
    "setfsuid",
    "setfsuid32",
    "setgroups",
    "setgroups32",
    "sethostname",
    "setresuid",
    "setresuid32",
    "setreuid",
    "setreuid32",
    "setuid",
    "setuid32",
    "vhangup",
];
const GROUP_PROCESS: &[&str] = &[
    "capget",
    "clone",
    "clone3",
    "execveat",
    "fork",
    "getrusage",
    "kill",
    "pidfd_open",
    "pidfd_send_signal",
    "prctl",
    "rt_sigqueueinfo",
    "rt_tgsigqueueinfo",
    "setns",
    "swapcontext",
    "tgkill",
    "times",
    "tkill",
    "unshare",
    "vfork",
    "wait4",
    "waitid",
    "waitpid",
];
const GROUP_RAW_IO: &[&str] = &[
    "ioperm",
    "iopl",
    "pciconfig_iobase",
    "pciconfig_read",
    "pciconfig_write",
    "s390_pci_mmio_read",
    "s390_pci_mmio_write",
];
const GROUP_REBOOT: &[&str] = &["kexec_file_load", "kexec_load", "reboot"];
const GROUP_RESOURCES: &[&str] = &[
    "ioprio_set",
    "mbind",
    "migrate_pages",
    "move_pages",
    "nice",
    "sched_setaffinity",
    "sched_setattr",
    "sched_setparam",
    "sched_setscheduler",
    "set_mempolicy",
    "set_mempolicy_home_node",
    "setpriority",
    "setrlimit",
];
const GROUP_SANDBOX: &[&str] = &[
    "landlock_add_rule",
    "landlock_create_ruleset",
    "landlock_restrict_self",
    "seccomp",
];
const GROUP_SETUID: &[&str] = &[
    "setgid",
    "setgid32",
    "setgroups",
    "setgroups32",
    "setregid",
    "setregid32",
    "setresgid",
    "setresgid32",
    "setresuid",
    "setresuid32",
    "setreuid",
    "setreuid32",
    "setuid",
    "setuid32",
];
const GROUP_SIGNAL: &[&str] = &[
    "rt_sigaction",
    "rt_sigpending",
    "rt_sigprocmask",
    "rt_sigsuspend",
    "rt_sigtimedwait",
    "rt_sigtimedwait_time64",
    "sigaction",
    "sigaltstack",
    "signal",
    "signalfd",
    "signalfd4",
    "sigpending",
    "sigprocmask",
    "sigsuspend",
];
const GROUP_SWAP: &[&str] = &["swapoff", "swapon"];
const GROUP_SYNC: &[&str] = &[
    "fdatasync",
    "fsync",
    "msync",
    "sync",
    "sync_file_range",
    "sync_file_range2",
    "syncfs",
];
const GROUP_SYSTEM_SERVICE: &[&str] = &[
    "@aio",
    "@basic-io",
    "@chown",
    "@default",
    "@file-system",
    "@io-event",
    "@ipc",
    "@keyring",
    "@memlock",
    "@network-io",
    "@process",
    "@resources",
    "@setuid",
    "@signal",
    "@sync",
    "@timer",
    "arm_fadvise64_64",
    "capget",
    "capset",
    "copy_file_range",
    "fadvise64",
    "fadvise64_64",
    "flock",
    "get_mempolicy",
    "getcpu",
    "getpriority",
    "ioctl",
    "ioprio_get",
    "kcmp",
    "madvise",
    "mremap",
    "name_to_handle_at",
    "oldolduname",
    "olduname",
    "personality",
    "readahead",
    "readdir",
    "remap_file_pages",
    "sched_get_priority_max",
    "sched_get_priority_min",
    "sched_getattr",
    "sched_getparam",
    "sched_getscheduler",
    "sched_rr_get_interval",
    "sched_rr_get_interval_time64",
    "sched_yield",
    "sendfile",
    "sendfile64",
    "setfsgid",
    "setfsgid32",
    "setfsuid",
    "setfsuid32",
    "setpgid",
    "setsid",
    "splice",
    "sysinfo",
    "tee",
    "umask",
    "uname",
    "userfaultfd",
    "vmsplice",
];
const GROUP_TIMER: &[&str] = &[
    "alarm",
    "getitimer",
    "setitimer",
    "timer_create",
    "timer_delete",
    "timer_getoverrun",
    "timer_gettime",
    "timer_gettime64",
    "timer_settime",
    "timer_settime64",
    "timerfd_create",
    "timerfd_gettime",
    "timerfd_gettime64",
    "timerfd_settime",
    "timerfd_settime64",
    "times",
];

pub(crate) fn group(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "@aio" => Some(GROUP_AIO),
        "@basic-io" => Some(GROUP_BASIC_IO),
        "@chown" => Some(GROUP_CHOWN),
        "@clock" => Some(GROUP_CLOCK),
        "@cpu-emulation" => Some(GROUP_CPU_EMULATION),
        "@debug" => Some(GROUP_DEBUG),
        "@default" => Some(GROUP_DEFAULT),
        "@file-system" => Some(GROUP_FILE_SYSTEM),
        "@io-event" => Some(GROUP_IO_EVENT),
        "@ipc" => Some(GROUP_IPC),
        "@keyring" => Some(GROUP_KEYRING),
        "@known" => Some(GROUP_KNOWN),
        "@memlock" => Some(GROUP_MEMLOCK),
        "@module" => Some(GROUP_MODULE),
        "@mount" => Some(GROUP_MOUNT),
        "@network-io" => Some(GROUP_NETWORK_IO),
        "@obsolete" => Some(GROUP_OBSOLETE),
        "@pkey" => Some(GROUP_PKEY),
        "@privileged" => Some(GROUP_PRIVILEGED),
        "@process" => Some(GROUP_PROCESS),
        "@raw-io" => Some(GROUP_RAW_IO),
        "@reboot" => Some(GROUP_REBOOT),
        "@resources" => Some(GROUP_RESOURCES),
        "@sandbox" => Some(GROUP_SANDBOX),
        "@setuid" => Some(GROUP_SETUID),
        "@signal" => Some(GROUP_SIGNAL),
        "@swap" => Some(GROUP_SWAP),
        "@sync" => Some(GROUP_SYNC),
        "@system-service" => Some(GROUP_SYSTEM_SERVICE),
        "@timer" => Some(GROUP_TIMER),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn system_service_contains_pinned_nested_sets() {
        let set = group("@system-service").unwrap();
        assert!(set.contains(&"@default"));
        assert!(set.contains(&"@network-io"));
        assert!(set.contains(&"@process"));
        assert!(set.contains(&"ioctl"));
    }
}
